In [1]:
import pandas as pd

# https://www.kaggle.com/datasets/oscarm524/predicting-returns-of-discounted-articles-sales?resource=download
df = pd.read_csv("./raw/orders_train.txt", sep=";")

print(df.dtypes)
df

orderID               str
orderDate             str
articleID             str
colorCode           int64
sizeCode              str
productGroup      float64
quantity            int64
price             float64
rrp               float64
voucherID             str
voucherAmount     float64
customerID            str
deviceID            int64
paymentMethod         str
returnQuantity      int64
dtype: object

,orderID,orderDate,articleID,colorCode,sizeCode,productGroup,quantity,price,rrp,voucherID,voucherAmount,customerID,deviceID,paymentMethod,returnQuantity
0,a1000001,2014-01-01,i1000382,1972,44,3.0,1,10.00,29.99,0,0.0,c1010575,2,BPRG,0
1,a1000001,2014-01-01,i1000550,3854,44,3.0,1,20.00,39.99,0,0.0,c1010575,2,BPRG,0
2,a1000002,2014-01-01,i1001991,2974,38,8.0,1,35.00,49.99,0,0.0,c1045905,4,BPRG,0
3,a1000002,2014-01-01,i1001999,1992,38,8.0,1,49.99,49.99,0,0.0,c1045905,4,BPRG,1
4,a1000003,2014-01-01,i1001942,1968,42,8.0,1,10.00,35.99,0,0.0,c1089295,2,PAYPALVC,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325160,a1744175,2015-09-30,i1003273,3096,40,3.0,1,35.99,35.99,0,0.0,c1055877,3,CBA,1
2325161,a1744176,2015-09-30,i1003256,2117,42,3.0,1,39.99,39.99,0,0.0,c1124916,2,CBA,0
2325162,a1744177,2015-09-30,i1001692,1001,38,8.0,1,20.00,29.99,0,0.0,c1168483,3,CBA,0
2325163,a1744177,2015-09-30,i1001757,1085,38,8.0,1,18.00,35.99,0,0.0,c1168483,3,CBA,0
2325164,a1744177,2015-09-30,i1001757,1097,38,8.0,1,18.00,35.99,0,0.0,c1168483,3,CBA,0

In [2]:
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://aaa:111@localhost:5433/ml_course_project")

df.to_sql("raw_orders", engine, if_exists="replace", index=False)

165

In [3]:
pd.read_sql("select * from raw_orders", engine)

,orderID,orderDate,articleID,colorCode,sizeCode,productGroup,quantity,price,rrp,voucherID,voucherAmount,customerID,deviceID,paymentMethod,returnQuantity
0,a1000001,2014-01-01,i1000382,1972,44,3.0,1,10.00,29.99,0,0.0,c1010575,2,BPRG,0
1,a1000001,2014-01-01,i1000550,3854,44,3.0,1,20.00,39.99,0,0.0,c1010575,2,BPRG,0
2,a1000002,2014-01-01,i1001991,2974,38,8.0,1,35.00,49.99,0,0.0,c1045905,4,BPRG,0
3,a1000002,2014-01-01,i1001999,1992,38,8.0,1,49.99,49.99,0,0.0,c1045905,4,BPRG,1
4,a1000003,2014-01-01,i1001942,1968,42,8.0,1,10.00,35.99,0,0.0,c1089295,2,PAYPALVC,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325160,a1744175,2015-09-30,i1003273,3096,40,3.0,1,35.99,35.99,0,0.0,c1055877,3,CBA,1
2325161,a1744176,2015-09-30,i1003256,2117,42,3.0,1,39.99,39.99,0,0.0,c1124916,2,CBA,0
2325162,a1744177,2015-09-30,i1001692,1001,38,8.0,1,20.00,29.99,0,0.0,c1168483,3,CBA,0
2325163,a1744177,2015-09-30,i1001757,1085,38,8.0,1,18.00,35.99,0,0.0,c1168483,3,CBA,0
2325164,a1744177,2015-09-30,i1001757,1097,38,8.0,1,18.00,35.99,0,0.0,c1168483,3,CBA,0

In [4]:
pd.read_sql("""
select
    count(*) as rows,
    count(distinct "customerID") as users,
    count(distinct "articleID") as items
from raw_orders
""", engine)

      rows   users  items
0  2325165  311369   3823